class Constants:
	ARTICLES_ON_HOME_PAGE = 3
	ARTICLES_ON_SHOW_ARTICLES_PAGE = 9
	ARTICLES_PER_USER_ARTICLES_PAGE = 5
	COMMENTS_PER_ARTICLE = 5
	COMPANIES_ON_SHOW_COMPANIES_PAGE = 8
	PRODUCTS_ON_SHOW_PRODUCTS_PAGE = 12

	BAD_REQUEST_ERROR_PAGE = 400
	COMING_SOON_PAGE = 401
	FORBIDDEN_PAGE_ERROR_PAGE = 403
	PAGE_NOT_FOUND_ERROR_PAGE = 404
	INTERNAL_SERVER_ERROR_PAGE = 500
	MAINTENANCE_PAGE = 503

	PROFILE_PICTURE_SIZE = 125
