import os, string
from PIL import Image
from flask import url_for, current_app
from flask_mail import Message
from app import mail
from flask_login import current_user


def save_picture(form_picture, old_picture):
	file_name, file_extension = os.path.splitext(form_picture.filename)

	if "default" not in file_name:
		random_hex = os.urandom(4).encode('hex')
		picture_filename = random_hex + file_extension
		picture_path = os.path.join(current_app.root_path, 'static/profilePics', picture_filename)
		output_size = (125, 125)
		image = Image.open(form_picture)
		image.thumbnail(output_size)
		image.save(picture_path)
	else:
		picture_filename = file_name + file_extension

	if "default" not in str(old_picture):
		delete_picture = os.path.join(current_app.root_path, "static/profilePics", old_picture)
		os.remove(delete_picture)

	return picture_filename


def send_reset_email(user):
	token = user.get_reset_token()
	message = Message("Password Reset Request", sender="theculture.noreply@gmail.com", recipients=[user.email])
	message.body = '''To reset your password, visit the following link:

{}

If you did not make this request, ignore this email and no changes will be made. If you believe your account has been compromised, visit www.theculture.herokuapp.com/reset_password.

Do not directly reply to this email, as this mailbox is not monitored.'''.format(url_for("users.reset_token", token=token, _external=True))

	mail.send(message)


us_states = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District Of Columbia",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

countries = {
	'AF': 'Afghanistan',
	'AL': 'Albania',
	'DZ': 'Algeria',
	'AS': 'American Samoa',
	'AD': 'Andorra',
	'AO': 'Angola',
	'AI': 'Anguilla',
	'AQ': 'Antarctica',
	'AG': 'Antigua and Barbuda',
	'AR': 'Argentina',
	'AM': 'Armenia',
	'AW': 'Aruba',
	'AU': 'Australia',
	'AT': 'Austria',
	'AZ': 'Azerbaijan',
	'BH': 'Bahrain',
	'BD': 'Bangladesh',
	'BB': 'Barbados',
	'BY': 'Belarus',
	'BE': 'Belgium',
	'BZ': 'Belize',
	'BJ': 'Benin',
	'BM': 'Bermuda',
	'BT': 'Bhutan',
	'BO': 'Bolivia',
	'BA': 'Bosnia and Herzegovina',
	'BW': 'Botswana',
	'BV': 'Bouvet Island',
	'BR': 'Brazil',
	'IO': 'British Indian Ocean Territory',
	'VG': 'British Virgin Islands',
	'BN': 'Brunei',
	'BG': 'Bulgaria',
	'BF': 'Burkina Faso',
	'BI': 'Burundi',
	'KH': 'Cambodia',
	'CM': 'Cameroon',
	'CA': 'Canada',
	'CV': 'Cape Verde',
	'KY': 'Cayman Islands',
	'CF': 'Central African Republic',
	'TD': 'Chad',
	'CL': 'Chile',
	'CN': 'China',
	'CX': 'Christmas Island',
	'CC': 'Cocos (Keeling) Islands',
	'CO': 'Colombia',
	'KM': 'Comoros',
	'CG': 'Congo',
	'CK': 'Cook Islands',
	'CR': 'Costa Rica',
	'HR': 'Croatia',
	'CU': 'Cuba',
	'CY': 'Cyprus',
	'CZ': 'Czech Republic',
	'CD': 'Democratic Republic of the Congo',
	'DK': 'Denmark',
	'DJ': 'Djibouti',
	'DM': 'Dominica',
	'DO': 'Dominican Republic',
	'TP': 'East Timor',
	'EC': 'Ecuador',
	'EG': 'Egypt',
	'SV': 'El Salvador',
	'GQ': 'Equatorial Guinea',
	'ER': 'Eritrea',
	'EE': 'Estonia',
	'ET': 'Ethiopia',
	'FO': 'Faeroe Islands',
	'FK': 'Falkland Islands',
	'FJ': 'Fiji',
	'FI': 'Finland',
	'MK': 'Former Yugoslav Republic of Macedonia',
	'FR': 'France',
	'FX': 'France, Metropolitan',
	'GF': 'French Guiana',
	'PF': 'French Polynesia',
	'TF': 'French Southern Territories',
	'GA': 'Gabon',
	'GE': 'Georgia',
	'DE': 'Germany',
	'GH': 'Ghana',
	'GI': 'Gibraltar',
	'GR': 'Greece',
	'GL': 'Greenland',
	'GD': 'Grenada',
	'GP': 'Guadeloupe',
	'GU': 'Guam',
	'GT': 'Guatemala',
	'GN': 'Guinea',
	'GW': 'Guinea-Bissau',
	'GY': 'Guyana',
	'HT': 'Haiti',
	'HM': 'Heard and Mc Donald Islands',
	'HN': 'Honduras',
	'HK': 'Hong Kong',
	'HU': 'Hungary',
	'IS': 'Iceland',
	'IN': 'India',
	'ID': 'Indonesia',
	'IR': 'Iran',
	'IQ': 'Iraq',
	'IE': 'Ireland',
	'IL': 'Israel',
	'IT': 'Italy',
	'JM': 'Jamaica',
	'JP': 'Japan',
	'JO': 'Jordan',
	'KZ': 'Kazakhstan',
	'KE': 'Kenya',
	'KI': 'Kiribati',
	'KW': 'Kuwait',
	'KG': 'Kyrgyzstan',
	'LA': 'Laos',
	'LV': 'Latvia',
	'LB': 'Lebanon',
	'LS': 'Lesotho',
	'LR': 'Liberia',
	'LY': 'Libya',
	'LI': 'Liechtenstein',
	'LT': 'Lithuania',
	'LU': 'Luxembourg',
	'MO': 'Macau',
	'MG': 'Madagascar',
	'MW': 'Malawi',
	'MY': 'Malaysia',
	'MV': 'Maldives',
	'ML': 'Mali',
	'MT': 'Malta',
	'MH': 'Marshall Islands',
	'MQ': 'Martinique',
	'MR': 'Mauritania',
	'MU': 'Mauritius',
	'YT': 'Mayotte',
	'MX': 'Mexico',
	'FM': 'Micronesia',
	'MD': 'Moldova',
	'MC': 'Monaco',
	'MN': 'Mongolia',
	'ME': 'Montenegro',
	'MS': 'Montserrat',
	'MA': 'Morocco',
	'MZ': 'Mozambique',
	'MM': 'Myanmar',
	'NA': 'Namibia',
	'NR': 'Nauru',
	'NP': 'Nepal',
	'NL': 'Netherlands',
	'AN': 'Netherlands Antilles',
	'NC': 'New Caledonia',
	'NZ': 'New Zealand',
	'NI': 'Nicaragua',
	'NE': 'Niger',
	'NG': 'Nigeria',
	'NU': 'Niue',
	'NF': 'Norfolk Island',
	'KP': 'North Korea',
	'MP': 'Northern Marianas',
	'NO': 'Norway',
	'OM': 'Oman',
	'PK': 'Pakistan',
	'PW': 'Palau',
	'PS': 'Palestine',
	'PA': 'Panama',
	'PG': 'Papua New Guinea',
	'PY': 'Paraguay',
	'PE': 'Peru',
	'PH': 'Philippines',
	'PN': 'Pitcairn Islands',
	'PL': 'Poland',
	'PT': 'Portugal',
	'PR': 'Puerto Rico',
	'QA': 'Qatar',
	'RE': 'Reunion',
	'RO': 'Romania',
	'RU': 'Russia',
	'RW': 'Rwanda',
	'SH': 'Saint Helena',
	'PM': 'St. Pierre and Miquelon',
	'KN': 'Saint Kitts and Nevis',
	'LC': 'Saint Lucia',
	'VC': 'Saint Vincent and the Grenadines',
	'WS': 'Samoa',
	'SM': 'San Marino',
	'SA': 'Saudi Arabia',
	'SN': 'Senegal',
	'RS': 'Serbia',
	'SC': 'Seychelles',
	'SL': 'Sierra Leone',
	'SG': 'Singapore',
	'SK': 'Slovakia',
	'SI': 'Slovenia',
	'SB': 'Solomon Islands',
	'SO': 'Somalia',
	'ZA': 'South Africa',
	'GS': 'South Georgia and the South Sandwich Islands',
	'KR': 'South Korea',
	'ES': 'Spain',
	'LK': 'Sri Lanka',
	'SD': 'Sudan',
	'SR': 'Suriname',
	'SJ': 'Svalbard and Jan Mayen Islands',
	'SZ': 'Swaziland',
	'SE': 'Sweden',
	'CH': 'Switzerland',
	'SY': 'Syria',
	'TW': 'Taiwan',
	'TJ': 'Tajikistan',
	'TZ': 'Tanzania',
	'TH': 'Thailand',
	'BS': 'The Bahamas',
	'GM': 'The Gambia',
	'TG': 'Togo',
	'TK': 'Tokelau',
	'TO': 'Tonga',
	'TT': 'Trinidad and Tobago',
	'TN': 'Tunisia',
	'TR': 'Turkey',
	'TM': 'Turkmenistan',
	'TC': 'Turks and Caicos Islands',
	'TV': 'Tuvalu',
	'VI': 'US Virgin Islands',
	'UG': 'Uganda',
	'UA': 'Ukraine',
	'AE': 'United Arab Emirates',
	'GB': 'United Kingdom',
	'US': 'United States',
	'UM': 'United States Minor Outlying Islands',
	'UY': 'Uruguay',
	'UZ': 'Uzbekistan',
	'VU': 'Vanuatu',
	'VA': 'Vatican City',
	'VE': 'Venezuela',
	'VN': 'Vietnam',
	'WF': 'Wallis and Futuna Islands',
	'EH': 'Western Sahara',
	'YE': 'Yemen',
	'ZM': 'Zambia',
	'ZW': 'Zimbabwe',
	'Other': 'Other'
}

country_codes = {
	'AF': '+93',
	'AL': '+355',
	'DZ': '+213',
	'AS': '+1',
	'AD': '+376',
	'AO': '+244',
	'AI': '+1',
	'AQ': '+672',
	'AG': '+1',
	'AR': '+54',
	'AM': '+374',
	'AW': '+297',
	'AU': '+61',
	'AT': '+43',
	'AZ': '+994',
	'BH': '+973',
	'BD': '+880',
	'BB': '+1',
	'BY': '+375',
	'BE': '+32',
	'BZ': '+501',
	'BJ': '+229',
	'BM': '+1',
	'BT': '+975',
	'BO': '+591',
	'BA': '+387',
	'BW': '+267',
	'BV': '+0',
	'BR': '+55',
	'IO': '+0',
	'VG': '+1',
	'BN': '+673',
	'BG': '+359',
	'BF': '+226',
	'BI': '+257',
	'CI': '+225',
	'KH': '+855',
	'CM': '+237',
	'CA': '+1',
	'CV': '+238',
	'KY': '+1',
	'CF': '+236',
	'TD': '+235',
	'CL': '+56',
	'CN': '+86',
	'CX': '+61',
	'CC': '+61',
	'CO': '+57',
	'KM': '+269',
	'CG': '+242',
	'CK': '+682',
	'CR': '+506',
	'HR': '+385',
	'CU': '+53',
	'CY': '+357',
	'CZ': '+420',
	'CD': '+243',
	'DK': '+45',
	'DJ': '+253',
	'DM': '+1',
	'DO': '+1',
	'TL': '+670',
	'EC': '+593',
	'EG': '+20',
	'SV': '+503',
	'GQ': '+240',
	'ER': '+291',
	'EE': '+372',
	'ET': '+251',
	'FO': '+298',
	'FK': '+500',
	'FJ': '+679',
	'FI': '+358',
	'MK': '+389',
	'FR': '+33',
	'GF': '+594',
	'PF': '+689',
	'TF': '+262',
	'GA': '+241',
	'GE': '+995',
	'DE': '+49',
	'GH': '+233',
	'GI': '+350',
	'GR': '+30',
	'GL': '+299',
	'GD': '+1',
	'GP': '+590',
	'GU': '+1',
	'GT': '+502',
	'GN': '+224',
	'GW': '+245',
	'GY': '+592',
	'HT': '+509',
	'HM': '+0',
	'HN': '+504',
	'HK': '+852',
	'HU': '+36',
	'IS': '+354',
	'IN': '+91',
	'ID': '+62',
	'IR': '+98',
	'IQ': '+964',
	'IE': '+353',
	'IL': '+972',
	'IT': '+39',
	'JM': '+1',
	'JP': '+81',
	'JO': '+962',
	'KZ': '+7',
	'KE': '+254',
	'KI': '+686',
	'KW': '+965',
	'KG': '+996',
	'LA': '+856',
	'LV': '+371',
	'LB': '+961',
	'LS': '+266',
	'LR': '+231',
	'LY': '+218',
	'LI': '+423',
	'LT': '+370',
	'LU': '+352',
	'MO': '+853',
	'MG': '+261',
	'MW': '+265',
	'MY': '+60',
	'MV': '+960',
	'ML': '+223',
	'MT': '+356',
	'MH': '+692',
	'MQ': '+596',
	'MR': '+222',
	'MU': '+230',
	'YT': '+262',
	'MX': '+52',
	'FM': '+691',
	'MD': '+373',
	'MC': '+377',
	'MN': '+976',
	'MS': '+1',
	'MA': '+212',
	'MZ': '+258',
	'MM': '+95',
	'NA': '+264',
	'NR': '+674',
	'NP': '+977',
	'NL': '+31',
	'AN': '+599',
	'NC': '+687',
	'NZ': '+64',
	'NI': '+505',
	'NE': '+227',
	'NG': '+234',
	'NU': '+683',
	'NF': '+672',
	'KP': '+850',
	'MP': '+1',
	'NO': '+47',
	'OM': '+968',
	'PK': '+92',
	'PW': '+680',
	'PA': '+507',
	'PG': '+675',
	'PY': '+595',
	'PE': '+51',
	'PH': '+63',
	'PN': '+870',
	'PL': '+48',
	'PT': '+351',
	'PR': '+1',
	'QA': '+974',
	'RE': '+262',
	'RO': '+40',
	'RU': '+7',
	'RW': '+250',
	'ST': '+239',
	'SH': '+290',
	'KN': '+1',
	'LC': '+1',
	'PM': '+508',
	'VC': '+1',
	'WS': '+685',
	'SM': '+378',
	'SA': '+966',
	'SN': '+221',
	'SC': '+248',
	'SL': '+232',
	'SG': '+65',
	'SK': '+421',
	'SI': '+386',
	'SB': '+677',
	'SO': '+252',
	'ZA': '+27',
	'GS': '+0',
	'KR': '+82',
	'ES': '+34',
	'LK': '+94',
	'SD': '+249',
	'SR': '+597',
	'SJ': '+0',
	'SZ': '+268',
	'SE': '+46',
	'CH': '+41',
	'SY': '+963',
	'TW': '+886',
	'TJ': '+992',
	'TZ': '+255',
	'TH': '+66',
	'BS': '+1',
	'GM': '+220',
	'TG': '+228',
	'TK': '+690',
	'TO': '+676',
	'TT': '+1',
	'TN': '+216',
	'TR': '+90',
	'TM': '+993',
	'TC': '+1',
	'TV': '+688',
	'VI': '+1',
	'UG': '+256',
	'UA': '+380',
	'AE': '+971',
	'GB': '+44',
	'US': '+1',
	'UM': '+0',
	'UY': '+598',
	'UZ': '+998',
	'VU': '+678',
	'VA': '+39',
	'VE': '+58',
	'VN': '+84',
	'WF': '+681',
	'EH': '+0',
	'YE': '+967',
	'YU': '+0',
	'ZM': '+260',
	'ZW': '+263'
}
