"""Removed image_file from all tables

Revision ID: 23028d45dcfe
Revises: 899ef92bc4de
Create Date: 2019-05-01 13:50:04.456513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23028d45dcfe'
down_revision = '899ef92bc4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'image_file')
    op.drop_column('product', 'image_file')
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('image_file', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('image_file', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
