"""empty message

Revision ID: 2828d591ac61
Revises: 
Create Date: 2019-03-22 10:55:55.952662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2828d591ac61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('article_id', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'comment_userId_fkey', 'comment', type_='foreignkey')
    op.drop_constraint(u'comment_reviewId_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_column('comment', 'reviewId')
    op.drop_column('comment', 'userId')
    op.add_column('review', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'review_userId_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'review', 'product', ['product_id'], ['id'])
    op.drop_column('review', 'userId')
    op.drop_column('review', 'views')
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('occupation', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'occupation')
    op.drop_column('user', 'bio')
    op.add_column('review', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('review', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(u'review_userId_fkey', 'review', 'user', ['userId'], ['id'])
    op.drop_column('review', 'user_id')
    op.drop_column('review', 'product_id')
    op.add_column('comment', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comment', sa.Column('reviewId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(u'comment_reviewId_fkey', 'comment', 'review', ['reviewId'], ['id'])
    op.create_foreign_key(u'comment_userId_fkey', 'comment', 'user', ['userId'], ['id'])
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'article_id')
    # ### end Alembic commands ###
