"""changed product.id to company.id in Article

Revision ID: 36c45fd0a832
Revises: 840020eadaf8
Create Date: 2019-02-17 13:37:09.896656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c45fd0a832'
down_revision = '840020eadaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'article_company_id_fkey', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key(u'article_company_id_fkey', 'article', 'product', ['company_id'], ['id'])
    # ### end Alembic commands ###
