"""removed company from reviews

Revision ID: 37421f4c9229
Revises: b2a63d7095e2
Create Date: 2019-02-17 12:28:01.363289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37421f4c9229'
down_revision = 'b2a63d7095e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'review_company_id_fkey', 'review', type_='foreignkey')
    op.drop_column('review', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'review_company_id_fkey', 'review', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###
