"""removed views from Review

Revision ID: 840020eadaf8
Revises: 37421f4c9229
Create Date: 2019-02-17 13:35:24.189808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840020eadaf8'
down_revision = '37421f4c9229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=50), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'comment', sa.Column('article_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'comment_review_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    op.drop_column(u'comment', 'review_id')
    op.drop_column(u'review', 'image_file')
    op.drop_column(u'review', 'views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'review', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'review', sa.Column('image_file', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column(u'comment', sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(u'comment_review_id_fkey', 'comment', 'review', ['review_id'], ['id'])
    op.drop_column(u'comment', 'article_id')
    op.drop_table('article')
    # ### end Alembic commands ###
