"""Removed image_file from all tables

Revision ID: 899ef92bc4de
Revises: bf703a430738
Create Date: 2019-04-30 21:50:51.519687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899ef92bc4de'
down_revision = 'bf703a430738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('image_file', sa.String(length=150), nullable=True))
    op.add_column('product', sa.Column('image_file', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('image_file', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    op.drop_column('product', 'image_file')
    op.drop_column('company', 'image_file')
    # ### end Alembic commands ###
