"""Removed image_file from all tables

Revision ID: 99106e5d2ecc
Revises: 
Create Date: 2019-04-26 10:06:52.657372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99106e5d2ecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image_file')
    op.drop_column('company', 'image_file')
    op.drop_column('product', 'image_file')
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('image_file', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('image_file', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('article', sa.Column('image_file', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
