"""Removed image_file from all tables

Revision ID: bf703a430738
Revises: b8301f5c5b32
Create Date: 2019-04-30 21:50:19.541400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf703a430738'
down_revision = 'b8301f5c5b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'image_file')
    op.drop_column('product', 'image_file')
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('image_file', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('image_file', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
